[wip] Refactor finalize processor
mmtk/mmtk-jikesrvm pull request #150
Opened 2023-09-26 01:25 UTC by fepicture

fix #145 

Current I only finish the finalizable processor refactor.

All tests for the current semispace have passed. I've rebased to the draft pull request.
 Changes:
- I implemented process_weak_refs which is invoked by a workbucket to process weak references.
  Internally, it uses jtoc_call to reuse existing JikesRVM methods.

2023-10-05 00:59 UTC, fepicture commented
@qinsoon thanks for your commit to update jikesrvm version. 
the test suite heap usage has been tested on my local (64GiB RAM, i9-12900H), but I do not know why will fail :p

2023-10-11 14:01 UTC, wks requested changes
The code should function properly, although there may be some hidden problems that prevent some tests from passing.  But JikesRVM is still one of our officially-supported VMs.  We run binding tests for some PRs (will soon become all PRs) of mmtk-core, and JikesRVM is one of the VMs to run binding tests with.  So I think it is not appropriate to merge this unstable change and disable some tests now.

I suggest we merge your change, but keep your change disabled by default.  That is, the MMTK-JikesRVM will still use the reference processors in mmtk-core.  But with a compile-time flag, MMTk-JikesRVM will use JikesRVM's reference/finalizer processors, instead.

You can use conditional compilation tricks to enable/disable the code.

For Rust code, you can use Cargo features.  You can add a feature, such as `binding_side_ref_proc` in `Cargo.toml`.  Inside Rust source files, you can use the attribute `#[cfg(feature = "binding_side_ref_proc")]` to selectively enable types, functions, blocks, statements, etc.  You can also use `if cfg!(feature = "binding_side_ref_proc")` to guard the control flow.

For Java code, you can just write `if SOME_CONSTANT { ... }`, and JikesRVM's compiler is smart enough to eliminate dead code.  I'll discuss more in the review comments in your PR in the `jikesrvm` repo.

For test scripts such as `ci-test-assertions.sh`, instead of commenting out failing tests and changing heap sizes, I suggest copy those scripts, save to different files (such as `ci-test-assertions-weakref.sh`), and edit the content there, including disabling failing tests and changing heap sizes. (p.s. You should change both `-Xms` and `-Xmx` so that on each line the `-Xms` and `-Xmx` are set to the same value.)

And you should create a compile script to compile `jikesrvm` plus `mmtk-jikesrvm` using your added conditional compilation flags.

2023-10-23 00:05 UTC, fepicture commented
hi @qinsoon， I have pushed a new commit to solve the comment

(basically, use conditional compile to keep the compatibility), 

can u activate the GitHub action workflow for this new commit?
 https://github.com/mmtk/mmtk-jikesrvm/actions/runs/6600465759

https://github.com/mmtk/mmtk-jikesrvm/actions/runs/6600465756

2023-10-23 00:09 UTC, qinsoon commented
> hi @qinsoon， I have pushed a new commit to solve the comment
> 
> (basically, use conditional compile to keep the compatibility),
> 
> can u activate the GitHub action workflow for this new commit? https://github.com/mmtk/mmtk-jikesrvm/actions/runs/6600465759
> 
> https://github.com/mmtk/mmtk-jikesrvm/actions/runs/6600465756

Yeah. I just did. I thought the workflows would be allowed as they were approved for the previous commit. I will keep an eye on the PR.

2023-10-23 00:10 UTC, fepicture commented
Thank you 🙇

2023-10-23 01:17 UTC, fepicture commented on mmtk/src/api.rs
> +pub extern "C" fn get_forwarded_object(object: ObjectReference) -> ObjectReference {
Currently, I've come across a tricky issue in JikesRVM. We first need to define `xxfunctionRIP` as an address to facilitate linking, correct? However, this `xxfunctionRIP` is a class member, and I haven't yet discovered a straightforward method for conditional compilation for it. As a result, our current approach to conditional compilation isn't optimal:
- In the ideal case, based on the feature flag, we should compile certain files and exclude others, ensuring no additional build overhead.
- In our present implementation, even if the feature isn't enabled, some files still get compiled.

To summarize, functions like `get_forwarded_object` will be compiled regardless of whether we activate the feature.

2023-10-24 07:17 UTC, wks commented on mmtk/src/api.rs
> +pub extern "C" fn get_forwarded_object(object: ObjectReference) -> ObjectReference {
OK.  In this case, we can let such functions exist even when the vm-side forwarding feature is not enabled, as long as existing CI test cases still run properly.

2023-10-24 07:22 UTC, wks approved these changes
Although not all tests passed, the current state of the code used conditional compilation and other techniques to keep the CI tests passing.  In this sense, it looks good to me.

We should keep working on this feature to make it stable so that we can eventually use VM-side weak ref and finalization processing by default.

2023-10-24 07:46 UTC, wks commented
A recent upstream change moved the method `is_emergency_collection` from `Plan` to `GlobalState`, but `GlobalState` is a private structure and inaccessible from the VM binding.  That prevents this PR from working.

The built-in reference processors and finalization processors can access the `MMTK::state` field because they are parts of the `mmtk` crate.  We should make change to `mmtk-core` and expose the `is_emergency_collection` function to the binding.

2023-10-24 07:49 UTC, fepicture commented
> A recent upstream change (https://github.com/mmtk/mmtk-core/commit/57af17fbfd94ff0df2cd3b1e504abe299ce4f0ab) moved the method `is_emergency_collection` from `Plan` to `GlobalState`, but `GlobalState` is a private structure and inaccessible from the VM binding.  That prevents this PR from working.
> 
> The built-in reference processors and finalization processors can access the `MMTK::state` field because they are parts of the `mmtk` crate.  We should make change to `mmtk-core` and expose the `is_emergency_collection` function to the binding.

thanks I will fix later.

2023-10-25 01:11 UTC, fepicture commented
hi, @qinsoon 

I have pushed a new commit to update with mmtk-core PR(expose the API for check emergency collection )

Plz activate the GitHub action workflow.

2023-10-25 01:59 UTC, wks commented
The "Dacapo Tests / test" failed with a known bug that existed before this PR was introduced.  I'll rerun the test.

2023-10-25 03:51 UTC, merged